# Generated by Django 5.2.6 on 2026-10-01 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvideo',
            options={'verbose_name_plural': 'Product Videos'},
        ),
        migrations.AddField(
            model_name='productvideo',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_videos', to='core.product'),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default='Illustrious Apparel', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video_file',
            field=models.FileField(upload_to='product-videos/'),
        ),
    ]
