# Generated by Django 5.2.6 on 2026-10-01 14:10

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_productvideo_options_productvideo_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvideo',
            options={},
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video_file',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='product-videos/'),
        ),
    ]
