# Generated by Django 5.2.6 on 2025-11-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
